name: cssify
description: >
  Generate and manage CSS styles programmatically in Dart. Effortlessly create responsive, maintainable, and dynamic CSS for your web projects—all from Dart.
version: 0.1.0
repository: https://github.com/bryanbill/cssify
homepage: https://pub.dev/packages/cssify
documentation: https://pub.dev/documentation/cssify/latest/
issue_tracker: https://github.com/bryanbill/cssify/issues

environment:
  sdk: ^3.8.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

topics:
  - css
  - web
  - style
  - responsive

funding:
  - https://github.com/sponsors/bryanbill