name: sample
description: An absolute bare-bones web app.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none
environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  web: ^0.5.1
  cssify:
    git:
      url: https://github.com/bryanbill/cssify.git

dev_dependencies:
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  lints: ^5.0.0
